title: Canterbury Food Bank
short_title: Canterbury Food Bank
description: A community project and registered charity providing emergency food parcels to individuals and families in short term financial crisis across the Canterbury District (Canterbury, Whitstable, Herne Bay and surrounding villages).
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  posts:
    output: true
  give:
    output: true
    permalink: "/give/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
